export { default as Service } from './Service.jsx'
export { default as Project } from './Project.jsx'
export { default as Coffee } from './Coffee.jsx'
export { default as QRcode } from './QRcode.jsx'
export { default as DesignParticles } from './DesignParticles.jsx'
export { default as Carousel } from './Carousel.jsx'
export { default as MyTimeline } from './MyTimeline.jsx'